# Generated by Django 2.2.6 on 2019-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191024_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
